#ifndef STDAFX_H
#define STDAFX_H

#include <cstdlib>

#define STBI_MSC_SECURE_CRT
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_IMAGE_RESIZE_IMPLEMENTATION

#endif STDAFX_H
